"""indexed semester id in subject table and taught by id in subject offering table

Revision ID: 106287b22b90
Revises: 230b214731c9
Create Date: 2026-03-14 17:15:29.844341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106287b22b90'
down_revision: Union[str, Sequence[str], None] = '230b214731c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subject_offerings_taught_by_id'), 'subject_offerings', ['taught_by_id'], unique=False)
    op.create_index(op.f('ix_subjects_semester_id'), 'subjects', ['semester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_semester_id'), table_name='subjects')
    op.drop_index(op.f('ix_subject_offerings_taught_by_id'), table_name='subject_offerings')
    # ### end Alembic commands ###
