"""fixed and refactored all the sql models

Revision ID: 16e1b50bd50a
Revises: c154f1b8bf61
Create Date: 2025-11-06 16:56:46.332331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16e1b50bd50a'
down_revision: Union[str, Sequence[str], None] = 'c154f1b8bf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_offerings_id'), 'subject_offerings', ['id'], unique=False)
    op.add_column('departments', sa.Column('department_name', sa.String(length=100), nullable=False))
    op.drop_constraint(op.f('departments_dept_name_key'), 'departments', type_='unique')
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_unique_constraint(None, 'departments', ['department_name'])
    op.drop_column('departments', 'dept_name')
    op.add_column('marks', sa.Column('final_exam_mark', sa.Float(), nullable=True))
    op.add_column('marks', sa.Column('GPA', sa.String(length=5), nullable=True))
    op.alter_column('marks', 'assignment_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('marks', 'midterm_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('marks', 'class_test_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('marks', 'total_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(op.f('marks_semester_id_fkey'), 'marks', type_='foreignkey')
    op.drop_constraint(op.f('marks_student_id_fkey'), 'marks', type_='foreignkey')
    op.drop_constraint(op.f('marks_subject_id_fkey'), 'marks', type_='foreignkey')
    op.create_foreign_key(None, 'marks', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'marks', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'marks', 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')
    op.drop_column('marks', 'letter_grade')
    op.drop_column('marks', 'fina_exam_mark')
    op.add_column('students', sa.Column('semester_id', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('students', 'session',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('students_department_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'semesters', ['semester_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subjects', 'subject_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('subjects_department_id_fkey'), 'subjects', type_='foreignkey')
    op.drop_constraint(op.f('subjects_semester_id_fkey'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'semesters', ['semester_id'], ['id'], ondelete='SET NULL')
    op.drop_column('subjects', 'department_id')

    # --- Ensure userrole enum exists ---
    userrole = postgresql.ENUM('admin', 'teacher', 'student', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)

    # --- Alter the column using explicit cast ---
    op.execute(
        """
        ALTER TABLE users 
        ALTER COLUMN role 
        TYPE userrole 
        USING role::text::userrole
        """
    )

    # op.alter_column('users', 'role',
    #            existing_type=sa.Enum('ADMIN', 'TEACHER', name='user_roles'),
    #            type_=userrole,
    #            existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
               type_=postgresql.ENUM('ADMIN', 'TEACHER', name='user_roles'),
               existing_nullable=False)
    op.add_column('subjects', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_semester_id_fkey'), 'subjects', 'semesters', ['semester_id'], ['id'])
    op.create_foreign_key(op.f('subjects_department_id_fkey'), 'subjects', 'departments', ['department_id'], ['id'])
    op.alter_column('subjects', 'subject_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_department_id_fkey'), 'students', 'departments', ['department_id'], ['id'])
    op.alter_column('students', 'session',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('students', 'user_id')
    op.drop_column('students', 'semester_id')
    op.add_column('marks', sa.Column('fina_exam_mark', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('marks', sa.Column('letter_grade', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.create_foreign_key(op.f('marks_subject_id_fkey'), 'marks', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('marks_student_id_fkey'), 'marks', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('marks_semester_id_fkey'), 'marks', 'semesters', ['semester_id'], ['id'])
    op.alter_column('marks', 'total_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('marks', 'class_test_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('marks', 'midterm_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('marks', 'assignment_mark',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('marks', 'GPA')
    op.drop_column('marks', 'final_exam_mark')
    op.add_column('departments', sa.Column('dept_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.create_unique_constraint(op.f('departments_dept_name_key'), 'departments', ['dept_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('departments', 'department_name')
    op.drop_index(op.f('ix_subject_offerings_id'), table_name='subject_offerings')
    op.drop_table('subject_offerings')
    # ### end Alembic commands ###
