"""added teachers name, subject title and subject code in index for faster searching

Revision ID: 2ef08ce98f1e
Revises: 8befd26b4eaa
Create Date: 2026-04-22 09:59:20.267261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef08ce98f1e'
down_revision: Union[str, Sequence[str], None] = '8befd26b4eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
