"""added all the tables with relations

Revision ID: 3d893509f124
Revises: 3c62ffbfa55a
Create Date: 2025-11-05 15:29:49.151309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d893509f124'
down_revision: Union[str, Sequence[str], None] = '3c62ffbfa55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('registration', sa.String(length=100), nullable=False),
    sa.Column('session', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_mark', sa.Float(), nullable=False),
    sa.Column('midterm_mark', sa.Float(), nullable=False),
    sa.Column('class_test_mark', sa.Float(), nullable=False),
    sa.Column('fina_exam_mark', sa.Float(), nullable=False),
    sa.Column('total_mark', sa.Float(), nullable=False),
    sa.Column('letter_grade', sa.String(length=5), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marks_id'), 'marks', ['id'], unique=False)
    op.add_column('subjects', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('subjects', sa.Column('semester_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'semesters', ['semester_id'], ['id'])
    op.create_foreign_key(None, 'subjects', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'semester_id')
    op.drop_column('subjects', 'department_id')
    op.drop_index(op.f('ix_marks_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
