"""fixed: added teachers name, subject title in index

Revision ID: 97def2afd9b6
Revises: 2ef08ce98f1e
Create Date: 2026-04-22 14:15:37.273893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97def2afd9b6'
down_revision: Union[str, Sequence[str], None] = '2ef08ce98f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subjects_subject_title'), 'subjects', ['subject_title'], unique=False)
    op.create_index(op.f('ix_teachers_name'), 'teachers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_name'), table_name='teachers')
    op.drop_index(op.f('ix_subjects_subject_title'), table_name='subjects')
    # ### end Alembic commands ###
